/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_appopencv_jni_ImgFun */

#ifndef _Included_com_appopencv_jni_ImgFun
#define _Included_com_appopencv_jni_ImgFun
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_appopencv_jni_ImgFun
 * Method:    testImg
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_appopencv_jni_ImgFun_testImg
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
