/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_grayprocess_jni_ImgProc */

#ifndef _Included_com_grayprocess_jni_ImgProc
#define _Included_com_grayprocess_jni_ImgProc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_grayprocess_jni_ImgProc
 * Method:    grayProc
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_grayprocess_jni_ImgProc_grayProc
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
